### ISSUE TITLE
Trouble using institutional login

### ISSUE THREAD

**Issue by fjwillemsen** [fjwillemsen/NativeOverleaf#3]
There is a problem when using Overleaf's [institutional login](https://www.overleaf.com/institutional-login): you may be redirected to your OS browser during the process, resulting in a failed login. I am currently working on solving this and have submitted a [bug issue to Nativefier](https://github.com/nativefier/nativefier/issues/1445) in the process. In the meantime, you can use the workaround described in the [troubleshooting section of the README](https://github.com/fjwillemsen/NativeOverleaf#institutional-login).

**Comment by fjwillemsen** [comment]
Resolved in accordance with the [Nativefier issue](https://github.com/nativefier/nativefier/issues/1445).

**Comment by fjwillemsen** [comment]
Resolved in accordance with the corresponding [Nativefier issue](https://github.com/nativefier/nativefier/issues/1445).

**Comment by Neowise33** [comment]
I still have an error message open in Chrome when logging into my KIT account (german university: Karlsruher Institut of Technology).
Deepl translation: 

Error
Outdated request
You probably see this message because you clicked the Back button on your web browser while you were on a secure web page or application. You may have also bookmarked the login page instead of the web page you want to access. Or you may have clicked on a link sent to you by someone who made the same mistake.

Without this check, some web browsers might create errors, or you would be redirected back to the application. Therefore, you will be shown this page instead.

**Comment by fjwillemsen** [comment]
I have fixed it for Karlsruher Institut of Technology in the [just released 1.7.4](https://github.com/fjwillemsen/NativeOverleaf/releases/latest). 
The way checking whether a URL should remain internal or go external (the root issue here) currently works is by checking a list of known sign-in providers, and a custom regex. [This regex](https://github.com/fjwillemsen/NativeOverleaf/blob/4ddeb34db41e9855cdc104f0703fa6097bd181b7/compile-all.sh#L60) currently matches URLs where the subdomain contains keywords like `profile`, `identity`, and `account`. I have added `idp` to fix it for KIT, but I'm reluctant to add too many non-explicit subdomains to avoid the application from not going external when it should. 

For others experiencing similar issues: feel free to suggest the subdomain to be added and I'll look in to it, but the easier way to circumvent this problem is by going to [overleaf.com](https://overleaf.com) &rarr; logging in via the desired institution &rarr; Account &rarr; Account Settings &rarr; Add another email. You should then be able to login in the application to the account directly via any email listed there.

**Comment by leahnsh** [comment]
I cannot log in using my university login details (Gottfried Wilhelm Leibniz University Hannover). We do not use our university email addresses to log in, but rather an assigned ID and password. Our accounts contain email addresses, but we cannot use them to log in. 

We use the university's WebSSO to log in. All information on this can be found here: https://www.uni-hannover.de/en/studium/im-studium/online-dienste
